version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Pass123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  userservice:
    build:
      context: .
      dockerfile: Dockerfile_user
    container_name: userservice
    ports:
      - "5001:8080"
    depends_on:
      - mongodb

  notesservice:
    build:
      context: .
      dockerfile: Dockerfile_notes
    container_name: notesservice
    ports:
      - "5002:8080"
    depends_on:
      - redis

  labelservice:
    build:
      context: .
      dockerfile: Dockerfile_label
    container_name: labelservice
    ports:
      - "5003:8080"
    depends_on:
      - sqlserver

  collaboratorservice:
    build:
      context: .
      dockerfile: Dockerfile_collaborator
    container_name: collaboratorservice
    ports:
      - "5004:8080"
    depends_on:
      - sqlserver
      - rabbitmq

  gateway:
    build:
      context: .
      dockerfile: Dockerfile_gateway
    container_name: gateway
    ports:
      - "7000:8080"
    depends_on:
      - userservice
      - notesservice
      - labelservice
      - collaboratorservice

volumes:
  sql_data:
  mongo_data: