using Microsoft.AspNetCore.Mvc;
using ProductApi.DTOs;
using ProductApi.Models;
using ProductApi.Services;


// Controller to handle API requests related to products
namespace ProductApi.Controllers
{
    [ApiController] // Indicates that this class is an API controller
    [Route("api/[controller]")] // Sets the URL route → "api/product" (controller name replaces [controller])
    public class ProductController : ControllerBase
    {
        private readonly ProductService _service;

        public ProductController(ProductService service)
        {
            _service = service;
        }

        [HttpPost]
        public IActionResult CreateProduct(ProductDTO dto) // Method to handle product creation, receives data from request body

        //IActionResult  = API response wrapper
        {
            var product = new Product // Create Product model object
            {
                Name = dto.Name,
                Price = dto.Price
                //id will be generated by the service/database, so we don't set it here
            };

            var result = _service.CreateProduct(product);// Call service to handle business logic

            return Ok(result); //Return HTTP 200 with result
        }




        [HttpGet] // Handles GET requests → api/product
        public IActionResult GetProducts()
        {
            var products = _service.GetProducts();
            return Ok(products); // Return list of products with HTTP 200
        }



        [HttpPut("{id}")] 
        public IActionResult UpdateProduct(int id, ProductDTO dto)
        {
            var product = new Product
            {
                Id = id,
                Name = dto.Name,
                Price = dto.Price
            };

            var result = _service.UpdateProduct(product);

            return Ok(result);
        }



        [HttpDelete("{id}")] //function to handle DELETE requests
        public IActionResult DeleteProduct(int id)
        {
            _service.DeleteProduct(id);
            return Ok("Deleted successfully");
        }
    }
}